version: '3.1'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: 'reservations_user'
      MYSQL_PASSWORD: 'student-door-shore-vertical'
      MYSQL_DATABASE: 'flight-reservations'
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3310:3306